### ISSUE TITLE
I like it, but can it do....

### ISSUE THREAD

**Issue by raarts** [codemeasandwich/redux-auto#3]
Hi,

I really like your approach, combining code in a structured way with handling async in a clear way. I discovered it too late, unfortunately, already went with redux-saga.. but still..

Can your solution handle [this concept](https://redux-saga.js.org/docs/advanced/NonBlockingCalls.html) as described in the saga tutorial?

And another question, is it possible to send async action from a component, set a `working` variable in the local state, and reset it when the async resolves, using a promise or something?

Also, does the init.js work with redux-persist?

**Comment by codemeasandwich** [comment]
Hi @raarts 
For the saga(Non blocking calls) can you give me a simple description of what you are trying to achieve? I can then tell you how to solve it in react-auto

For a async. Take a look at [chaining](https://github.com/codemeasandwich/redux-auto#chaining-action-together) and [async+ui](https://github.com/codemeasandwich/redux-auto#handling-async-actions-in-your-ui)

I think you could add you redux-persist code into the [index](https://github.com/codemeasandwich/redux-auto#default) for that part of your store.

**Comment by raarts** [comment]
> For the saga(Non blocking calls) can you give me a simple description of what you are trying to achieve? I can then tell you how to solve it in react-auto

A simple example would be handling a multi-step form (btw this is all for react-native).
The form comprises multiple steps, in my case, fill in your phone number, press 'validate'. This does two things, call a remote API, and present a PIN to the user. The remote API calls the phone number, asking for the PIN. As soon as the PIN is accepted, a notification is sent to the phone, and the form should present success (and redirect the user to the list of validated phone numbers - with the new one added.

What I do now with redux-saga is start a background saga, which sets the form state (which resides in the store) to 'working' and calls the API. Setting the form state will cause a re-render of the form, showing a spinner.
The saga in the mean time waits for the API to succeed, and if so, sets a random PIN in the store, and sets the form state to 'enterpin'. This will rerender the form, showing the PIN to the user. Now we're waiting from the notification from the backend that the PIN was entered correctly. This will trigger a redux action (where the saga has been waiting on), and the saga will fire another API call (requesting the list of validated phonenumbers, and navigate the user to the new list.

This is not a complete description, but you get my drift.

This approach has a few problems. One of it is that the form state is kept in the store, and I feel that's inappropriate, I need to create a lot of code in reducers etc surrounding that, and I feel it belongs in the store.

Also error handling isn't nice. For the API calls I need to create a new saga which handles canceling, etc anyway if you look at the link I added, this ends up in multiple functions with lots of conditional checks.

I was hoping all this could be easier with redux-auto.

> I think you could add you redux-persist code into the index for that part of your store.

I'm putting my entire store in redux persist, and add a few exceptions. Is there a generic index.js for that?

**Comment by codemeasandwich** [comment]
What do you mean by ?

> notification is sent to the phone

As the client's API call can just wait for the server to reply with PIN ok or not.. or connection timeout.

A very quick outline on how I would solve your problem, taking that notification was handled by another redux-middleware.

	store/nav/index.js ------------------------------------------------

	export default function (nav = defaults, action)
	{
	  if("@notification/pin" === action.type && action.meta.ok){
               return {...nav, page:"list"}
          }
	}

	store/phone/add.js ------------------------------------------------

	//...

	action({number}){
	  return fetch('https://api.b.c/?validate='+number)
	}

	store/phone/index.js ------------------------------------------------

	export default function (phone = defaults, action)
	{
	  if("@notification/pin" === action.type && action.meta.addPhone){
               return {...phone, new_number:action.meta.addPhone}
          }
	}

	ui/something.jsx ------------------------------------------------

	let content = <button onClick={()=>actions.phone.add({number:"+12344345"})}>
	click me
	</button>

	  if(false === this.props.phone.status.add){
	     content = <Modal> enter you PIN <input placeholder="your PIN"/> <button onClick={()=>actions.phone.pin({ ... })}> <Modal>
	  } else if( this.props.phone.status.add instanceof Error ){
	     content = this.props.phone.status.add.message
	  }

	<Page>{ content }<Page>

I do believe [chaining](https://github.com/codemeasandwich/redux-auto#chaining-action-together) and [async+ui](https://github.com/codemeasandwich/redux-auto#handling-async-actions-in-your-ui) can handle this

----

As for the persist. you can hydrate when you crate the store. OR in each index.js listen of the redux-persist action type.

You can foke the [example](https://github.com/codemeasandwich/redux-auto/tree/master/example) and install `redux-persist`. Then I can take a look :)

OR if you can port the example to react native I could help you more
