### ISSUE TITLE
Require webpack?

### ISSUE THREAD

**Issue by GollyJer** [codemeasandwich/redux-auto#4]
Hi.  I stumbled on your approach form a question you answered on [stackoverflow](https://stackoverflow.com/questions/40517999/redux-alternative).

It seems pretty awesome. I like the self documenting concept.
Does it require webpack?  I'm building with React Native and am not sure how to approach giving this a try.

Best,
Jeremy

**Comment by codemeasandwich** [comment]
Hi @GollyJer 

I have not used `React Native` 
From what I can read, you will need to set this up with **bundling** but should be possible.

There is a lot of people talking about this but I couldnt find a clear answer to loading a folder.

From the Redux-Auto side: It's ok to do this as a static require at build time as you need all your store/reduces code and this will not change at run time. Only the require need to support a run-time string.

Please let me know how you get on and if you have any example code.

**Comment by GollyJer** [comment]
Cool. Thanks!
After reading a little more I think I'm going to give MobX a try for my next project and if I don't like it go back to Redux and give Redux-Auto a try.
