### ISSUE TITLE
Chaining Example is invalid; throws reducer error 

### ISSUE THREAD

**Issue by jschimmoeller** [codemeasandwich/redux-auto#5]
Per you example in chaining:

export function fulfilled (user, payload, userFromServer){
  return userFromServer;
} fulfilled.chain = (user, payload, userFromServer) => actions.nav.move({page:"home"})

export function rejected (user, payload, userFromServer){
  return userFromServer;
} rejected.chain = actions.user.reset

both of these reducers dispatch another action but this causes the following exception to be thrown:

createStore.js:160 Uncaught (in promise) Error: Reducers may not dispatch actions.

**Comment by jschimmoeller** [comment]
if you wrap them in a setTimeout (making them async) it will work

**Comment by codemeasandwich** [comment]
@jschimmoeller 
Thanks for the bug report. 
I have reproduce the problem in a test case and am working on a fix :)

**Comment by codemeasandwich** [comment]
**Fixed** and live as **v1.9.1** on npm

**Comment by jschimmoeller** [comment]
just tested it works great; thanks for the quick fix
