### ISSUE TITLE
Uncaught Error: file reducer.test in account/tests contains a DOT in its name

### ISSUE THREAD

**Issue by brandondurham** [codemeasandwich/redux-auto#9]
My store tests have filenames that look like `reducer.test.js`. When starting my app I’m getting the following error:

```
Uncaught Error: file reducer.test in account/tests contains a DOT in its name
```

Changing the name to `reducer-test.js` resolves the issue, but that’s not the format I want. Hundreds of tests across my entire app share the same filename format.

How can I work around this?

**Comment by brandondurham** [comment]
In fact, if I could just have `redux-auto` ignore certain directories, that would be fine.

**Comment by codemeasandwich** [comment]
Hi @brandondurham 
thank you for reporting the problem, and sorry for the delay. I have pushed a new version 2.1.0 to [npm](https://www.npmjs.com/package/redux-auto) that should fix the case of having test files in you store

For you ref. Here is the change:
https://github.com/codemeasandwich/redux-auto/commit/54bfb66fed086d3992c239671e780f1559e5e252

Please let me know how you get on.
